### ISSUE TITLE
Can you give null safety support for this plugin?

### ISSUE THREAD

**Issue by dnsoumik** [jakebonk/FlutterBoardView#10]
I can help you if you need any help :)

**Comment by mrruby** [comment]
Please +1

**Comment by jakebonk** [comment]
Sure I can try and get to it this weekend!

**Comment by jakebonk** [comment]
Just pushed it let me know if it worked for you at I can close this issue!

**Comment by dnsoumik** [comment]
Thanks for the release it worked for me :+1:

**Comment by arshkinana** [comment]
Closing the issue as the plugin is null-safe
