### ISSUE TITLE
How to retain board scroll position

### ISSUE THREAD

**Issue by hillelcoren** [jakebonk/FlutterBoardView#12]
Thanks for creating this package!

We're connecting the board to a REST API and would like to update it after we've saved the data to the server. The challenge is the scroll position is lost when the widget is recreated. 

Is it possible to track the scroll position and then set the position when the widget is rebuilt?

**Comment by jakebonk** [comment]
I haven't tested this code but you can get the scroll offsets by doing this. 
``` dart
BoardViewController bvController = new BoardViewController();

double offset = bvController.state.boardViewController.offset; // This would be the boardview scroll position
bcController.state.listStates.forEach((element) async{
    double offset = element.boardListController.offset;//This would be the scroll position of a board list
});
```
I would then create a new ScrollController after the position would be lost by setting the old offset
``` dart
bvController.state.boardViewController = new ScrollController(initialScrollOffset:offset);
```

**Comment by hillelcoren** [comment]
Thanks for the code! I'll try it out...

Would you consider exposing the scroll controller as a parameter when creating the BoardViewController?

**Comment by jakebonk** [comment]
No problem! Yeah this library is overdue for an update. When I get some free time I plan on moving most things to the BoardViewController and make it more robust and web ready. I also plan on adding animations to it some point

**Comment by hillelcoren** [comment]
That's great to hear!! We're working to add it to [our app](https://github.com/invoiceninja/admin-portal), the package has been really helpful. Thanks for your work on it!
