### ISSUE TITLE
Vertical Board

### ISSUE THREAD

**Issue by Dhananjayan-PN** [jakebonk/FlutterBoardView#5]
Can you also add a Vertical direction as well? It is more convenient and useful that way. It will be very helpful.
Great package btw.

**Comment by jakebonk** [comment]
I don't plan on adding a vertical direction to this package but I did make a separate package for a vertical style BoardView.

Link: https://github.com/jakebonk/FlutterChecklistView

The structure of both are pretty similar so it should work just the same

**Comment by Dhananjayan-PN** [comment]
Hi Jake,
Thanks a lot for letting me know about the other package. That is exactly what I was looking for. Thanks for your contribution to Flutter by creating awesome packages.
